using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CIS152FinalMcCurdyV1.Models;

namespace CIS152FinalMcCurdyV1.Data
{
    public class DrinkShopAppContext : DbContext
    {
        public DrinkShopAppContext (DbContextOptions<DrinkShopAppContext> options)
            : base(options)
        {
        }

        public DbSet<CIS152FinalMcCurdyV1.Models.Drink> Drink { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Customer> Customer { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Order> Order { get; set; } = default!;

        //public DbSet<CIS152FinalMcCurdyV1.Models.ToDo> ToDo { get; set; } = default!;

        // above 4 DbSets was auto generated - tutorials varied some pluralized the table
        // names and others had table name as singular. The autogenerated migrations
        // w/ EF appears to use singular form for tables. 
        /*public DbSet<CIS152FinalMcCurdyV1.Models.Drink> Drinks { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Customer> Customers { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Order> Orders { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.ToDo> ToDoes { get; set; } = default!;*/

    }
}
