using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CIS152FinalMcCurdyV1.Models;

namespace CIS152FinalMcCurdyV1.Data
{
    public class DrinkShopAppContext : DbContext
    {
        public DrinkShopAppContext (DbContextOptions<DrinkShopAppContext> options)
            : base(options)
        {
        }

        public DbSet<CIS152FinalMcCurdyV1.Models.Drink> Drink { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Customer> Customer { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Order> Order { get; set; } = default!;

        //public DbSet<CIS152FinalMcCurdyV1.Models.ToDo> ToDo { get; set; } = default!;

        // above 4 DbSets was auto generated - tutorials varied some pluralized the table
        // names and others had table name as singular. The autogenerated migrations
        // w/ EF appears to use singular form for tables. 
        /*public DbSet<CIS152FinalMcCurdyV1.Models.Drink> Drinks { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Customer> Customers { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.Order> Orders { get; set; } = default!;

        public DbSet<CIS152FinalMcCurdyV1.Models.ToDo> ToDoes { get; set; } = default!;*/
        
        /*public override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);*/

            /*modelBuilder.Entity<Customer>()
                .ToTable("Customer");
            modelBuilder.Entity<Customer>()
                .Property(x => x.CustomerId);*/


            /*modelBuilder.Entity<Order>()
                .ToTable("Order");
            modelBuilder.Entity<Drink>()
                .ToTable("Drink");*/


            //var customer = new List<Customer>
            /*var customers = new List<Customer>
                {
                new Customer{FirstName="Carsons",LastName="Alexa",Email="acarson@fake.edu", Phone="222-444-5555"},
                new Customer{FirstName="Meridian",LastName="Andrea",Email="ameridian@fake.edu"},
                new Customer{FirstName="Archibalt",LastName="Arturo",Email="aarchibalt@fake.edu", Phone="222-555-8855"},
                new Customer{FirstName="Baracus",LastName="BA",Email="babaracus@fake.edu"},
                new Customer{FirstName="Yang",LastName="Ying",Email="yyang@fake.edu", Phone="222-333-4455"},
                new Customer{FirstName="Prevails",LastName="Justice",Email="jprevails@fake.edu"},
                new Customer{FirstName="Oswald",LastName="Norman",Email="greengoblin@fake.org", Phone="222-222-3535"},
                new Customer{FirstName="Twist",LastName="Oliver",Email="otwist@fake.edu"}
                };
            
            modelBuilder.Entity<Customer>().HasData(customers);*/
            //modelBuilder.Entity<Customer>().HasData(customers.ForEach(c => Customer.Add(c)););

            //customer.ForEach(c => context.Customer.Add(c));
            /*customers.ForEach(c => context.Customer.Add(c));
            context.SaveChanges();*/
            /*customers.ForEach(c => Customer.Add(c));
            SaveChanges();

            //base.OnModelCreating(modelBuilder);
        }*/
    }
}
