// <auto-generated />
using System;
using CIS152FinalMcCurdyV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS152FinalMcCurdyV1.Migrations
{
    [DbContext(typeof(DrinkShopAppContext))]
    partial class DrinkShopAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrinkId"));

                    b.Property<string>("DrinkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrinkName")
                        .HasColumnType("int");

                    b.Property<decimal>("DrinkPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DrinkSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrinkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("DrinkId");

                    b.HasIndex("OrderId");

                    b.ToTable("Drink");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ToDoId")
                        .HasColumnType("int");

                    b.Property<int?>("ToDoId1")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ToDoId");

                    b.HasIndex("ToDoId1");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToDoId"));

                    b.Property<DateTime>("ToDoDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ToDoId");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.Drink", b =>
                {
                    b.HasOne("CIS152FinalMcCurdyV1.Models.Order", "Order")
                        .WithMany("Drinks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.Order", b =>
                {
                    b.HasOne("CIS152FinalMcCurdyV1.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIS152FinalMcCurdyV1.Models.ToDo", null)
                        .WithMany("Orders")
                        .HasForeignKey("ToDoId");

                    b.HasOne("CIS152FinalMcCurdyV1.Models.ToDo", null)
                        .WithMany("OrdersQueue")
                        .HasForeignKey("ToDoId1");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.Order", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("CIS152FinalMcCurdyV1.Models.ToDo", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("OrdersQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
